name: anti_tinder_2
description: Anti Tinder 2.0, le retour de l'application encore plus VENER.FR

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  swipe_cards: ^1.0.0
  cupertino_icons: ^1.0.2
  event_bus: ^2.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
